sequenceDiagram
    title New Note Sequence Diagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
    activate server
    Note right of browser : Request data : note = {note written in the input field}
    server-->>browser: HTTP Response : (Status Code : 302, Location: /exampleapp/notes, ...)
    deactivate server

    Note right of browser: Interprets status code 302 to make a GET Request to {Location}

    browser->>server: GET /exampleapp/notes
    activate server
    server-->>browser: HTML Document
    deactivate server

    browser->>server: GET /exampleapp/main.css
    activate server
    server-->>browser: the CSS file
    deactivate server

    browser->>server: GET /exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    Note right of browser: The browser starts executing the JS code that fetches the JSON file from the server

    browser->>server: GET /exampleapp/data.json
    activate server
    server-->>browser: [{ "content": "HTML is easy", "date": "2026-08-01..." }, ... ]
    deactivate server

    Note right of browser: The browser executes the callback function that renders the notes to the DOM
